import { notifyEvent } from './notificationService.js'

const send = (businessId, event) => notifyEvent(businessId, event)
const entityId = (record) => record.purchaseOrderId || record.orderId || record.receivingId || record.paymentId || record.returnId || record.transactionId || record.userId || record._id

export const notificationEvents = {
  purchaseCreated: (businessId, order) => send(businessId, { dedupeKey: `purchase:${entityId(order)}:created`, type: 'PURCHASE_ORDER_CREATED', category: 'purchases', severity: 'info', title: `Purchase order ${order.orderNumber} created`, message: `${order.supplierName} · ${order.items.length} item line(s).`, relatedEntity: 'PurchaseOrder', relatedEntityId: entityId(order), navigationTarget: 'Purchase Orders' }),
  purchaseStatus: (businessId, order) => send(businessId, { dedupeKey: `purchase:${entityId(order)}:status:${order.status}`, type: order.status === 'Cancelled' ? 'ORDER_CANCELLED' : 'PURCHASE_ORDER_STATUS_CHANGED', category: 'purchases', severity: order.status === 'Cancelled' ? 'warning' : 'info', title: `${order.orderNumber} is now ${order.status}`, message: `Purchase order for ${order.supplierName} changed status.`, relatedEntity: 'PurchaseOrder', relatedEntityId: entityId(order), navigationTarget: 'Purchase Orders' }),
  salesCreated: (businessId, order) => send(businessId, { dedupeKey: `sale:${entityId(order)}:created`, type: 'SALES_ORDER_CREATED', category: 'sales', severity: 'info', title: `Sales order ${order.orderNumber} created`, message: `${order.customerName} · ${order.items.length} item line(s).`, relatedEntity: 'SalesOrder', relatedEntityId: entityId(order), navigationTarget: 'Orders' }),
  salesStatus: (businessId, order) => send(businessId, { dedupeKey: `sale:${entityId(order)}:status:${order.status}`, type: order.status === 'Cancelled' ? 'ORDER_CANCELLED' : 'SALES_ORDER_STATUS_CHANGED', category: 'sales', severity: order.status === 'Cancelled' ? 'warning' : 'success', title: `${order.orderNumber} is ${order.status}`, message: `Sales order for ${order.customerName} changed status.`, relatedEntity: 'SalesOrder', relatedEntityId: entityId(order), navigationTarget: 'Orders' }),
  received: (businessId, receipt) => send(businessId, { dedupeKey: `receiving:${entityId(receipt)}:created`, type: 'PURCHASE_RECEIVED', category: 'purchases', severity: 'success', title: 'Purchase stock received', message: `${receipt.items.reduce((sum, item) => sum + item.acceptedQuantity, 0)} accepted unit(s) were added to inventory.`, relatedEntity: 'Receiving', relatedEntityId: entityId(receipt), navigationTarget: 'Receiving' }),
  payment: (businessId, payment) => send(businessId, { dedupeKey: `payment:${entityId(payment)}:recorded`, type: 'PAYMENT_RECORDED', category: 'payments', severity: 'success', title: `${payment.type === 'purchase' ? 'Supplier' : 'Customer'} payment recorded`, message: `${payment.amount} paid by ${payment.paymentMethod}.`, relatedEntity: 'Payment', relatedEntityId: entityId(payment), navigationTarget: 'Payments' }),
  returned: (businessId, record) => send(businessId, { dedupeKey: `return:${entityId(record)}:created`, type: record.type === 'purchase' ? 'PURCHASE_RETURN' : 'SALES_RETURN', category: 'returns', severity: 'warning', title: `${record.type === 'purchase' ? 'Purchase' : 'Sales'} return completed`, message: `${record.quantity} × ${record.productName} · ${record.reason}.`, relatedEntity: 'Return', relatedEntityId: entityId(record), navigationTarget: record.type === 'purchase' ? 'Purchase Returns' : 'Returns' }),
  inventory: (businessId, result) => send(businessId, { dedupeKey: `inventory:${entityId(result.transaction)}:created`, type: result.transaction.type === 'adjustment' ? 'INVENTORY_ADJUSTMENT' : 'STOCK_MOVEMENT', category: 'inventory', severity: result.transaction.type === 'adjustment' ? 'warning' : 'info', title: result.transaction.type === 'adjustment' ? 'Inventory adjusted' : 'Stock movement recorded', message: `${result.product.name}: ${result.transaction.previousStock} → ${result.transaction.newStock}.`, relatedEntity: 'Product', relatedEntityId: result.product.productId, navigationTarget: 'Stock History' }),
  member: (businessId, member, action) => send(businessId, { dedupeKey: `member:${entityId(member)}:${action}:${Date.now()}`, type: 'USER_MANAGEMENT_CHANGED', category: 'users', severity: 'info', title: action === 'created' ? 'Team member added' : 'Team member updated', message: `${member.name} (${member.roleId}) is ${member.status}.`, relatedEntity: 'Member', relatedEntityId: entityId(member), navigationTarget: 'Users' }),
  role: (businessId, role, action) => send(businessId, { dedupeKey: `role:${role.roleId}:${action}:${Date.now()}`, type: 'ROLE_PERMISSIONS_CHANGED', category: 'users', severity: 'warning', title: action === 'permissions' ? 'Role permissions changed' : 'Role saved', message: `${role.name} now has ${role.permissions.length} permission(s).`, relatedEntity: 'Role', relatedEntityId: role.roleId, navigationTarget: action === 'permissions' ? 'Permissions' : 'Roles' }),
}
